name: Build and Deploy to Workers
on:
  schedule:
    - cron: '*/30 15-19 * * TUE'
    - cron: '*/30 7-10 * * WED'
    - cron: '0 */8 * * *'
  workflow_dispatch:
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - run: npm ci
    - run: ./build.sh
    - run: npx wrangler deploy
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
